dbt_youhodler_dev:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: localhost
      port: 1433
      database: reportprod
      schema: dev
      user: sa
      password: P@ssW0rd!
      trust_cert: true